CREATE TABLE [adi].[CCLF6] (
    [adiH_CCLF6_SKey]         INT           IDENTITY (1, 1) NOT NULL,
    [CUR_CLM_UNIQ_ID]         VARCHAR (13)  NULL,
    [CLM_LINE_NUM]            VARCHAR (10)  NULL,
    [BENE_MBI_ID]             VARCHAR (11)  NULL,
    [BENE_HIC_NUM]            VARCHAR (11)  NULL,
    [CLM_TYPE_CD]             VARCHAR (2)   NULL,
    [CLM_FROM_DT]             DATE          NULL,
    [CLM_THRU_DT]             DATE          NULL,
    [CLM_FED_TYPE_SRVC_CD]    CHAR (1)      NULL,
    [CLM_POS_CD]              VARCHAR (2)   NULL,
    [CLM_LINE_FROM_DT]        DATE          NULL,
    [CLM_LINE_THRU_DT]        DATE          NULL,
    [CLM_LINE_HCPCS_CD]       VARCHAR (5)   NULL,
    [CLM_LINE_CVRD_PD_AMT]    VARCHAR (15)  NULL,
    [CLM_PRMRY_PYR_CD]        CHAR (1)      NULL,
    [PAYTO_PRVDR_NPI_NUM]     VARCHAR (10)  NULL,
    [ORDRG_PRVDR_NPI_NUM]     VARCHAR (10)  NULL,
    [CLM_CARR_PMT_DNL_CD]     VARCHAR (2)   NULL,
    [CLM_PRCSG_IND_CD]        VARCHAR (2)   NULL,
    [CLM_ADJSMT_TYPE_CD]      VARCHAR (2)   NULL,
    [CLM_EFCTV_DT]            DATE          NULL,
    [CLM_IDR_LD-DT]           DATE          NULL,
    [CLM_CNTL_NUM]            VARCHAR (40)  NULL,
    [BENE_EQTBL_BIC_HICN_NUM] VARCHAR (11)  NULL,
    [CLM_LINE_ALOWD_CHRG_AMT] VARCHAR (17)  NULL,
    [CLM_DISP_CD]             VARCHAR (2)   NULL,
    [SrcFileName]             VARCHAR (100) NULL,
    [FileDate]                DATE          NULL,
    [OriginalFileName]        VARCHAR (100) NULL,
    [CreateDate]              DATETIME      NULL,
    [CreateBy]                VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([adiH_CCLF6_SKey] ASC)
);

