CREATE TABLE [adi].[CCLF7] (
    [adiCCLF7_SKey]                INT           IDENTITY (1, 1) NOT NULL,
    [CUR_CLM_UNIQ_ID]              VARCHAR (13)  NULL,
    [BENE_MBI_ID]                  VARCHAR (11)  NULL,
    [BENE_HIC_NUM]                 VARCHAR (11)  NULL,
    [CLM_LINE_NDC_CD]              VARCHAR (11)  NULL,
    [CLM_TYPE_CD]                  VARCHAR (2)   NULL,
    [CLM_LINE_FROM_DT]             DATE          NULL,
    [PRVDR_SRVC_ID_QLFYR_CD]       VARCHAR (2)   NULL,
    [CLM_SRVC_PRVDR_GNRC_ID_NUM]   VARCHAR (20)  NULL,
    [CLM_DSPNSNG_STUS_CD]          CHAR (1)      NULL,
    [CLM_DAW_PROD_SLCTN_CD]        CHAR (1)      NULL,
    [CLM_LINE_SRVC_UNIT_QTY]       NUMERIC (18)  NULL,
    [CLM_LINE_DAYS_SUPLY_QTY]      NUMERIC (18)  NULL,
    [PRVDR_PRSBNG_ID_QLFYR_CD]     CHAR (2)      NULL,
    [CLM_PRSBNG_PRVDR_GNRC_ID_NUM] NUMERIC (18)  NULL,
    [CLM_LINE_BENE_PMT_AMT]        MONEY         NULL,
    [CLM_ADJSMT_TYPE_CD]           VARCHAR (2)   NULL,
    [CLM_EFCTV_DT]                 DATE          NULL,
    [CLM_IDR_LD_DT]                DATE          NULL,
    [CLM_LINE_RX_SRVC_RFRNC_NUM]   VARCHAR (12)  NULL,
    [CLM_LINE_RX_FILL_NUM]         VARCHAR (9)   NULL,
    [CLM_PHRMCY_SRVC_TYPE_CD]      VARCHAR (2)   NULL,
    [SrcFileName]                  VARCHAR (100) NULL,
    [FileDate]                     DATE          NULL,
    [OriginalFileName]             VARCHAR (100) NULL,
    [CreateDate]                   DATETIME      NULL,
    [CreateBy]                     VARCHAR (100) NULL,
    [AstCreatedDate]               DATETIME      NULL,
    [AstCreatedBy]                 VARCHAR (100) NULL,
    PRIMARY KEY CLUSTERED ([adiCCLF7_SKey] ASC)
);

